name: check-code
on:
  workflow_dispatch:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
            
      - name: Qodana - Linters
        uses: JetBrains/qodana-action@v3.2.1
        
      - name: Save Qodana's results to artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/qodana
          
      - uses: actions/download-artifact@v2
        with:
          path: qodana
          
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./qodana/report
          destination_dir: ./
